# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    router: false
    session: false

when@test:
    framework:
        test: true
