name: retumador

services:

  php:
    build:
      context: ./.docker/php
    volumes:
      - .:/var/www

  nginx:
    image: nginx:latest
    ports:
      - '8087:80'
    volumes:
      - ./public:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
