#!/usr/bin/env php
<?php

use Retumador\Kernel;
use Retumador\Command\CrawlCommand;
use Symfony\Component\Console\SingleCommandApplication;
use Symfony\Component\Console\Application;

if (!is_dir(__DIR__.'/vendor')) {
    throw new LogicException('Dependencies are missing. Try running "composer install".');
}

if (!is_file(__DIR__.'/vendor/autoload_runtime.php')) {
    throw new LogicException('Symfony Runtime is missing. Try running "composer require symfony/runtime".');
}

require_once __DIR__.'/vendor/autoload_runtime.php';

return function (array $context) {
    $kernel = new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);
    $kernel->boot();

    /** @var CrawlCommand $command */
    $command = $kernel->getContainer()->get(CrawlCommand::class);

    $application = new Application('Retumador', '0.1');
    $application->add($command);
    $application->setDefaultCommand((string) $command->getName(), true);

    return $application;
};
