#!/usr/bin/env php
<?php

use Retumador\Kernel;
use Retumador\Application;

if (!is_dir(__DIR__.'/vendor')) {
    throw new LogicException('Dependencies are missing. Try running "composer install".');
}

if (!is_file(__DIR__.'/vendor/autoload_runtime.php')) {
    throw new LogicException('Symfony Runtime is missing. Try running "composer require symfony/runtime".');
}

require_once __DIR__.'/vendor/autoload_runtime.php';

return function (array $context) {
    /* @phpstan-ignore argument.type */
    $kernel = new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);

    return new Application($kernel);
};
