name: Release

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: 🚀 Publish container on hub.docker.com
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Download dependencies
        uses: ramsey/composer-install@v3
        env:
          APP_ENV: prod
          APP_DEBUG: false
        with:
          composer-options: "--no-dev --optimize-autoloader"

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: odolbeau/retumador:latest
